Repository qri-io/registry, pull requests merged in 2018-11, with the labels that each got.

#17 test(mocks): expand mock test funcs
  pinset_test.go
  regserver/mock/server.go
  regserver/mock/server_test.go
Labels: in progress, test

#16 feat(reputation): most basic handler added for `/reputation` endpoint
  .circleci/config.yml
  regclient/reputation.go
  regclient/reputation_test.go
  registry.go
  regserver/handlers/reputation.go
  regserver/handlers/reputation_test.go
  regserver/handlers/routes.go
  reputation.go
  reputation_test.go
  reputations.go
Labels: in progress

#18 fix(dataset): support getting dataset info
  ns/context.go
  ns/context_test.go
  ns/ref.go
  ns/ref_test.go
  regclient/dataset.go
  regserver/handlers/dataset.go
  regserver/handlers/dataset_test.go
  regserver/handlers/routes.go
Labels: fix, in progress

#20 refactor(dataset): laying groundwork for ListDataset and returning datasets based on limit and offset
  regclient/dataset.go
  regclient/dataset_test.go
  regserver/handlers/dataset.go
Labels: in progress

#22 refactor(regClient): `GetDataset` func should return a `registry.Dataset`, not a `dataset.DatasetPod`
  regclient/dataset.go
Labels: in progress
