Repository qri-io/registry, pull requests merged in 2019-02, with the labels that each got.

#25 refactor: integrate dataset package refactoring
  dataset.go
  dataset_test.go
  datasets_test.go
  regclient/dataset.go
  regclient/dataset_test.go
  regserver/handlers/dataset.go
  regserver/handlers/dataset_test.go
  regserver/handlers/handlers.go
  regserver/mock/server.go
Labels: in progress, refactor

#26 fix(pin status polling): fix defer/goroutine deadlock
  regclient/pin.go
Labels: fix, in progress

#27 fix(mockserver): May add datasets to mock registry server
  regserver/mock/server.go
Labels: in progress
